package sbnz.integracija;

import sbnz.integracija.facts.User;
import sbnz.integracija.enumeration.Gender;
import sbnz.integracija.enumeration.Goal;

/*rule "Set activity - very light"
	agenda-group "activity"
    when
        $user: User(activity == Activity.VERY_LIGHT)
    then
        $user.setActivityCount(1.3);
        update($user);
end

rule "Set activity - light"
	agenda-group "activity"
    when
        $user: User(activity == Activity.LIGHT)
    then
        $user.setActivityCount(1.55);
        update($user);
end

rule "Set activity - moderate"
	agenda-group "activity"
    when
        $user: User(activity == Activity.MODERATE)
    then
        $user.setActivityCount(1.65);
        update($user);
end

rule "Set activity - heavy "
	agenda-group "activity"
    when
        $user: User(activity == Activity.HEAVY)
    then
        $user.setActivityCount(1.8);
        update($user);
end

rule "Set activity - very heavy"
	agenda-group "activity"
    when
        $user: User(activity == Activity.VERY_HEAVY)
    then
        $user.setActivityCount(2.0);
        update($user);
end


rule "Calculate daily calorie intake for men"
	agenda-group "activity"	
	salience -100
    when
    	$user: User(gender == Gender.MALE, activityCount != null, $calories: (weight * 1.0 * 24.0 * activityCount))
    then
    	System.out.println($calories);
        $user.setRecommendedDailyCalories($calories);
        update($user);
end

rule "Calculate daily calorie intake for women"
	agenda-group "activity"
	salience -100
    when
    	$user: User(gender == Gender.FEMALE, activityCount != null, $calories: (weight * 0.9 * 24.0 * activityCount))
    then
        $user.setRecommendedDailyCalories($calories);
        update($user);
end

rule "Goal gain weight"
	agenda-group "activity"
	salience -200
	lock-on-active true
    when
    	$user: User(recommendedDailyCalories != null, goal == Goal.GAIN_WEIGHT, $recommended: (recommendedDailyCalories * 1.5))
    then
        $user.setRecommendedDailyCalories($recommended);
        update($user);
end

rule "Goal lose weight"
	agenda-group "activity"
	salience -200
	lock-on-active true
    when
    	$user: User(recommendedDailyCalories != null, goal == Goal.LOSE_WEIGHT, $recommended: (recommendedDailyCalories * 0.5))
    then
        $user.setRecommendedDailyCalories($recommended);
        update($user);
end

rule "Goal gain muscle"
	agenda-group "activity"
	salience -200
	lock-on-active true
    when
    	$user: User(recommendedDailyCalories != null, goal == Goal.GAIN_MUSCLE, $recommended: (recommendedDailyCalories * 1.3))
    then
        $user.setRecommendedDailyCalories($recommended);
        update($user);
end

rule "Goal lose muscle"
	agenda-group "activity"
	salience -200
	lock-on-active true
    when
    	$user: User(recommendedDailyCalories != null, goal == Goal.LOSE_MUSCLE, $recommended: (recommendedDailyCalories * 0.7))
    then
        $user.setRecommendedDailyCalories($recommended);
        update($user);
end

rule "Goal stagnate"
	agenda-group "activity"
	salience -200
	lock-on-active true
	when
		$user: User(recommendedDailyCalories != null, goal == Goal.STAGNATE, $recommended: (recommendedDailyCalories));
	then
		$user.setRecommendedDailyCalories($recommended);
		update($user);
end	

*/