package sbnz.integracija;

import sbnz.integracija.facts.User;
import sbnz.integracija.enumeration.Gender;
import sbnz.integracija.enumeration.Goal;


rule "Set activity - very light"
	agenda-group "activity"
    when
        $user: User(activity == Activity.VERY_LIGHT)
    then
        $user.setActivityCount(1.3);
        update($user);
end

rule "Set activity - light"
	agenda-group "activity"
    when
        $user: User(activity == Activity.LIGHT)
    then
        $user.setActivityCount(1.55);
        update($user);
end

rule "Set activity - moderate"
	agenda-group "activity"
    when
        $user: User(activity == Activity.MODERATE)
    then
        $user.setActivityCount(1.65);
        update($user);
end

rule "Set activity - heavy "
	agenda-group "activity"
    when
        $user: User(activity == Activity.HEAVY)
    then
        $user.setActivityCount(1.8);
        update($user);
end

rule "Set activity - very heavy"
	agenda-group "activity"
    when
        $user: User(activity == Activity.VERY_HEAVY)
    then
        $user.setActivityCount(2.0);
        update($user);
end

rule "Calculate daily calorie intake for men"
	agenda-group "activity"	
	salience -100
    when
    	$user: User(gender == Gender.MALE, activityCount != null, $calories: (weight * 1.0 * 24.0 * activityCount))
    then
        $user.setDailyCalorieIntake($calories);
        update($user);
end

rule "Calculate daily calorie intake for women"
	agenda-group "activity"
	salience -100
    when
    	$user: User(gender == Gender.FEMALE, activityCount != null, $calories: (weight * 0.9 * 24.0 * activityCount))
    then
        $user.setDailyCalorieIntake($calories);
        update($user);
end

rule "Goal gain weight"
	agenda-group "activity"
    when
    	$user: User(goal == Goal.GAIN_WEIGHT, $recommended: (dailyCalorieIntake * 1.5))
    then
        $user.setDailyCalorieIntake($recommended);
        update($user);
end

rule "Goal lose weight"
	agenda-group "activity"
    when
    	$user: User(goal == Goal.LOSE_WEIGHT, $recommended: (dailyCalorieIntake * 0.5))
    then
        $user.setDailyCalorieIntake($recommended);
        System.out.println($recommended);
        update($user);
end

rule "Goal gain musle"
	agenda-group "activity"
    when
    	$user: User(goal == Goal.GAIN_MUSCLE, $recommended: (dailyCalorieIntake * 1.3))
    then
        $user.setDailyCalorieIntake($recommended);
        update($user);
end

rule "Goal lose muscle"
	agenda-group "activity"
    when
    	$user: User(goal == Goal.LOSE_MUSCLE, $recommended: (dailyCalorieIntake * 0.7))
    then
        $user.setDailyCalorieIntake($recommended);
        update($user);
end