package sbnz.integracija;
import sbnz.integracija.facts.User;
import sbnz.integracija.facts.MealHistory;
import sbnz.integracija.facts.DailyMeal;
import sbnz.integracija.facts.Meal;
import java.util.List;
global List<HistoryMeal> meals;

rule "New"
	agenda-group "dailyCalories"
	when 
		$mealHistory: MealHistory($meals: meals)
		accumulate(
		 	DailyMeal($quantity: quantity, $meal: meal) from $meals
		 	and Meal($calories: calories) from $meal,
		 	$total: sum($calories*$quantity)
		 )
	then
		System.out.println($total);
		
end
