package sbnz.integracija;

import sbnz.integracija.facts.User;

/*rule "Check daily calories status"
	agenda-group "calories"
	no-loop
	lock-on-active true
    when    
    	 $u : User(recommendedDailyCalories != null);
    	 $mealHistory: MealHistory($meals: meals);
    	 $meal:  Meal( $meal memberOf $meals )
         accumulate ( 
         		$calories : Meal( $calories memberOf $meals );
        		$count : count($calories)
        		)
    then
    	modify($d){ setNumIngredients($count); }
end/*

